# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04\x64\x61ta\"\x1f\n\x0fSaveDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"#\n\x10SaveDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x10\n\x0eGetDataRequest\"\x1f\n\x0fGetDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x80\x01\n\x0b\x44\x61taService\x12\x39\n\x08SaveData\x12\x15.data.SaveDataRequest\x1a\x16.data.SaveDataResponse\x12\x36\n\x07GetData\x12\x14.data.GetDataRequest\x1a\x15.data.GetDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAVEDATAREQUEST']._serialized_start=20
  _globals['_SAVEDATAREQUEST']._serialized_end=51
  _globals['_SAVEDATARESPONSE']._serialized_start=53
  _globals['_SAVEDATARESPONSE']._serialized_end=88
  _globals['_GETDATAREQUEST']._serialized_start=90
  _globals['_GETDATAREQUEST']._serialized_end=106
  _globals['_GETDATARESPONSE']._serialized_start=108
  _globals['_GETDATARESPONSE']._serialized_end=139
  _globals['_DATASERVICE']._serialized_start=142
  _globals['_DATASERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
